name: fluorescent-fibre-counting
channels:
- defaults
dependencies:
- h5py=2.7.0=np113py36_0
- numpy=1.13.1=py36_0
- pandas=0.20.3=py36_0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_1
- python=3.6.2=0
- pytest=3.2.1
- scikit-learn=0.19.0
- holoviews=1.8.3=py36_0
- matplotlib=2.0.2=np113py36_0
- bokeh=0.12.9=py36h7e0c046_0
- pip:
  - keras==2.0.8
  - tensorflow==1.2
  - networkx==1.11
  - hyperopt==0.1
  - opencv-python==3.3.0.10
  - opencv-contrib-python==3.3.0.10
